### ISSUE TITLE
signInAndRetrieveDataWithCredential is deprecated

### ISSUE THREAD

**Issue by rhashimoto** [msukmanowsky/gapi-firebase#1]
Thanks for publishing this! It's very helpful.

Just a note that [signInAndRetrieveDataWithCredential](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signinandretrievedatawithcredential) is now deprecated in favor of [signInWithCredential](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signinwithcredential). It appears to be [merely a name change](https://github.com/firebase/firebase-js-sdk/blob/90b5f044b136211a39f891c05788bc46de1d2927/packages/auth/src/auth.js#L1604-L1609).

**Comment by msukmanowsky** [comment]
Thanks for the heads up! Updated.
